### ISSUE TITLE
fine tuning时报错，是训练集的问题吗？

### ISSUE THREAD

**Issue by hai4john** [JiangWeibeta/ELIC#2]
fine tuning时，报如下错误，是对训练集的尺寸有要求吗？
24-04-10 10:36:36.398 - INFO: Learning rate: 0.0001
Traceback (most recent call last):
  File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/playground/train.py", line 162, in <module>
    main()
  File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/playground/train.py", line 124, in main
    current_step = train_one_epoch(
  File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/utils/training.py", line 24, in train_one_epoch
    optimizer.step()
  File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 166, in step
    adam(
  File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 316, in adam
    func(params,
  File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 520, in _multi_tensor_adam
    torch._foreach_lerp_(device_exp_avgs, device_grads, 1 - beta1)
RuntimeError: The size of tensor a (32) must match the size of tensor b (192) at non-singleton dimension 0

**Comment by hai4john** [comment]
有看到 dataload部分
    train_transforms = transforms.Compose(
        [transforms.RandomCrop(args.patch_size), transforms.ToTensor()]
    )
对图像进行裁剪，理论上只要数据集中图片尺寸大于 args.patch_size 就行，对吧？

**Comment by hai4john** [comment]
贴错地方了
